apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: registrer-tilretteleggingsbehov
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - https://registrer-tilretteleggingsbehov.dev.intern.nav.no
        - https://registrer-tilretteleggingsbehov.intern.dev.nav.no
    liveness:
        initialDelay: 5
        path: /registrer-tilretteleggingsbehov/internal/isAlive
    readiness:
        initialDelay: 5
        path: /registrer-tilretteleggingsbehov/internal/isReady
