name: Bygg og deploy

on: [push]

env:
    IMAGE: docker.pkg.github.com/${{ github.repository }}/registrer-tilretteleggingsbehov:${{ github.sha }}

jobs:
    bygg-og-push-docker-image:
        name: Bygg applikasjon
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
                      server/package-lock.json
            - name: Installer avhengigheter
              run: npm ci
            - name: Bygg applikasjon
              run: npm run build
            - name: Installer avhengigheter for server
              run: cd server && npm ci
            - name: Bygg server
              run: cd server && npm run build
            - name: Bygg og publiser Docker-image
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  docker build --tag ${IMAGE} .
                  echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
                  docker push ${IMAGE}

    deploy-til-dev-fss:
        name: Deploy til dev-fss
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/oppgraderinger'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-fss
                  RESOURCE: nais-dev-fss.yaml

    deploy-to-prod-fss:
        name: Deploy til prod-fss
        needs: deploy-til-dev-fss
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-fss
                  RESOURCE: nais-prod-fss.yaml

    deploy-til-dev-gcp:
        name: Deploy til dev-gcp
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/oppgraderinger'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais-dev-gcp.yaml

    deploy-to-prod-gcp:
        name: Deploy til prod-gcp
        needs: deploy-til-dev-gcp
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais-prod-gcp.yaml

    oppdater-gh-pages:
        name: Update GitHub pages
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Installer avhengigheter
              run: npm ci
            - name: Build mock application
              run: npm run build:mock
            - name: Oppdater GitHub pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
