name: Bygg og deploy

on: [push]

env:
    IMAGE: ghcr.io/${{ github.repository }}/registrer-tilretteleggingsbehov:${{ github.sha }}

jobs:
    bygg-og-push-docker-image:
        name: Bygg applikasjon
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
                      server/package-lock.json
            - name: Installer avhengigheter
              run: npm ci
            - name: Bygg applikasjon
              run: npm run build
            - name: Installer avhengigheter for server
              run: cd server && npm ci
            - name: Bygg server
              run: cd server && npm run build
            - name: Logg inn til Github
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Bygg og publiser Docker-image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{ env.IMAGE }}

    deploy-til-dev-gcp:
        name: Deploy til dev-gcp
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/readonly'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais-dev-gcp.yaml

    deploy-to-prod-gcp:
        name: Deploy til prod-gcp
        needs: deploy-til-dev-gcp
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais-prod-gcp.yaml

    oppdater-gh-pages:
        name: Update GitHub pages
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '12.x'
            - name: Installer avhengigheter
              run: npm ci
            - name: Build mock application
              run: npm run build:mock
            - name: Oppdater GitHub pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
